name: system-tests-backend

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  system-test:
    runs-on: ubuntu-latest
    env:
      SENTRY_URL: http://127.0.0.1:8000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@7e48093f71aa12588241894ff3695e83c4b5e4b0 # pin@v2.4.2

#      - name: Cache Gradle packages
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-

#       Without this android-ndk submodule caused problems
#       Build could probably be speed up by removing this and fixing the actual issue
#      - name: Make compile without tests
#        run: make compileWithoutTests

      - name: Exclude android modules from build
        run: |
          sed -i -e '/.*"sentry-android-ndk",/d' -e '/.*"sentry-android",/d' -e '/.*"sentry-android-core",/d' -e '/.*"sentry-android-integration-tests:sentry-uitest-android-benchmark",/d' -e '/.*"sentry-android-integration-tests:sentry-uitest-android",/d' -e '/.*"sentry-android-integration-tests:test-app-sentry",/d' settings.gradle.kts

      - name: Exclude android modules from ignore list
        run: |
          sed -i -e '/.*"sentry-uitest-android",/d' -e '/.*"sentry-uitest-android-benchmark",/d' -e '/.*"test-app-sentry",/d' build.gradle.kts

      - name: Start server and run integration test for sentry-cli commands
        run: |
          test/system-test-sentry-server-start.sh & ./gradlew :sentry-samples:sentry-samples-spring-boot-jakarta:bootJar && test/system-test-spring-server-start.sh & test/wait-for-spring.sh && ./gradlew :sentry-samples:sentry-samples-spring-boot-jakarta:systemTest
